##### Numpy Array 

In [562]:
import numpy as np 

In [563]:
# Struktur data : Array
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [564]:
a = [1, 2, 3]
np.array(a)

array([1, 2, 3])

In [565]:
b = [[1, 2, 3], [4, 5, 6]]
np.array(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [566]:
arr_b = np.array(b)
arr_b.shape # ordo

(2, 3)

In [567]:
c = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(c)
arr_c = np.array(c)
arr_c.shape 

(3, 3)

In [568]:
arr_c.dtype # tipe data

dtype('int32')

In [569]:
arr_c.reshape(1, 9) # 2,3 error

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [570]:
np.append(arr_c, 10)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [571]:
# reassign
arr_c = np.append(arr_c, 10)
arr_c 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Indexing dan Slicing pada Array

In [572]:
c = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(c)
arr_c = np.array(c)

In [573]:
arr_c[0,1] # akses elemen

2

In [574]:
arr_c[0, 0:3] # akses baris 0 kolom 0-2

array([1, 2, 3])

In [575]:
arr_c[0, ]

array([1, 2, 3])

##### Operation pada Array

In [576]:
arr_c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [577]:
# arithmetic operation
arr_c+arr_c #arr_c+7 dst

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [578]:
# boolean operation
arr_c>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [579]:
filter_arr = arr_c<= 3
arr_c[filter_arr] # filter array

array([1, 2, 3])

##### Matrrix Operation

In [580]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [581]:
# dot product
np.dot(a, b) # bisa pakai a @ b ; a.dot(b)

32

In [582]:
# cross product
np.cross(a, b) # a x b

array([-3,  6, -3])

In [583]:
arr_c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [584]:
# inverse
np.linalg.inv(arr_c) # invers matriks

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [585]:
# transpose
np.transpose(arr_c) # transpose matriks

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [586]:
# determinant
np.linalg.det(arr_c) # determinan matriks

-9.51619735392994e-16

In [587]:
# eigen value dan eigen vector
np.linalg.eig(arr_c) 

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))

In [588]:
# biar rapi
eigval, eigvec = np.linalg.eig(arr_c)
print("Eigen Value: ", eigval)
print("Eigen Vector: ", eigvec)

Eigen Value:  [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigen Vector:  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
